import type {
  Course,
  IngestionCandidate,
  LearningPath,
  Provider,
  SkillDefinition,
  SourceConfig,
  SourceRun,
  Topic,
  UserCourseStatus,
  UserPreferences,
  UserProfile,
} from "@/lib/types";

const now = "2026-03-15T12:00:00.000Z";
const catalogVerifiedAt = "2026-03-15T09:00:00.000Z";

const topicSeed = [
  ["topic-llm", "llm", "LLM", "Large language model foundations and applied patterns."],
  ["topic-slm", "slm", "SLM", "Small language model deployment and optimization."],
  ["topic-mcp", "mcp", "MCP", "Model Context Protocol tooling and integrations."],
  ["topic-genai", "generative-ai", "Generative AI", "Core generative AI workflows and ecosystem knowledge."],
  ["topic-ml", "machine-learning", "Machine Learning", "Classical ML fundamentals and model evaluation."],
  ["topic-prompt", "prompt-engineering", "Prompt Engineering", "Prompt design, evaluation, and guardrails."],
  ["topic-rag", "rag", "RAG", "Retrieval-augmented generation systems and design."],
  ["topic-vector", "vector-databases", "Vector Databases", "Indexing, embeddings, and retrieval infrastructure."],
  ["topic-agents", "ai-agents", "AI Agents", "Agent planning, tool use, and orchestration."],
  ["topic-finetune", "fine-tuning", "Fine-Tuning", "Adaptation strategies for language models."],
  ["topic-eval", "evaluation", "Evaluation", "Offline and online evaluation for AI systems."],
  ["topic-mlops", "mlops", "MLOps", "Operational practices for ML systems."],
  ["topic-rai", "responsible-ai", "Responsible AI", "Safety, policy, governance, and bias mitigation."],
  ["topic-python", "python-foundations", "Python Foundations", "Python basics for AI practitioners."],
  ["topic-stats", "statistics", "Statistics", "Statistics and experimentation basics for ML."],
 ] as const;

export const topics: Topic[] = topicSeed.map(([id, slug, name, description]) => ({
  id,
  slug,
  name,
  description,
  isActive: true,
}));

export const skills: SkillDefinition[] = [
  {
    id: "skill-rag-architecture",
    slug: "rag-architecture",
    name: "RAG architecture",
    description: "Design retrieval, ranking, and grounding workflows.",
    topicId: "topic-rag",
    levelHint: "amateur",
  },
  {
    id: "skill-prompt-evals",
    slug: "prompt-evals",
    name: "Prompt evaluation",
    description: "Design prompt tests, scorecards, and regression suites.",
    topicId: "topic-prompt",
    levelHint: "amateur",
  },
  {
    id: "skill-model-selection",
    slug: "model-selection",
    name: "Model selection",
    description: "Choose between LLM, SLM, and deployment tradeoffs.",
    topicId: "topic-llm",
    levelHint: "basic",
  },
  {
    id: "skill-agent-tooling",
    slug: "agent-tooling",
    name: "Agent tooling",
    description: "Integrate tools, memory, and execution loops.",
    topicId: "topic-agents",
    levelHint: "professional",
  },
  {
    id: "skill-safety-review",
    slug: "safety-review",
    name: "Safety review",
    description: "Assess risk and mitigation patterns for production AI systems.",
    topicId: "topic-rai",
    levelHint: "professional",
  },
  {
    id: "skill-feature-engineering",
    slug: "feature-engineering",
    name: "Feature engineering",
    description: "Work with tabular modeling inputs and experiments.",
    topicId: "topic-ml",
    levelHint: "basic",
  },
];

export const providers: Provider[] = [
  {
    id: "provider-coursera",
    name: "Coursera",
    websiteUrl: "https://www.coursera.org",
    providerType: "mooc",
    isActive: true,
  },
  {
    id: "provider-deeplearning",
    name: "DeepLearning.AI",
    websiteUrl: "https://www.deeplearning.ai",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-hf",
    name: "Hugging Face",
    websiteUrl: "https://huggingface.co",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-openai",
    name: "OpenAI",
    websiteUrl: "https://openai.com",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-anthropic",
    name: "Anthropic",
    websiteUrl: "https://www.anthropic.com",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-linkedin",
    name: "LinkedIn",
    websiteUrl: "https://www.linkedin.com",
    providerType: "mooc",
    isActive: true,
  },
  {
    id: "provider-microsoft",
    name: "Microsoft",
    websiteUrl: "https://www.microsoft.com",
    providerType: "docs",
    isActive: true,
  },
  {
    id: "provider-ibm",
    name: "IBM",
    websiteUrl: "https://www.ibm.com",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-aws",
    name: "Amazon Web Services",
    websiteUrl: "https://aws.amazon.com",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-google",
    name: "Google",
    websiteUrl: "https://cloud.google.com",
    providerType: "docs",
    isActive: true,
  },
  {
    id: "provider-perplexity",
    name: "Perplexity",
    websiteUrl: "https://www.perplexity.ai",
    providerType: "docs",
    isActive: true,
  },
  {
    id: "provider-meta",
    name: "Meta",
    websiteUrl: "https://www.meta.com",
    providerType: "community",
    isActive: true,
  },
  {
    id: "provider-tesla",
    name: "Tesla",
    websiteUrl: "https://www.tesla.com",
    providerType: "other",
    isActive: true,
  },
];

export const courses: Course[] = [
  {
    id: "course-llm-foundations",
    title: "LLM Foundations for Builders",
    summary: "A free, self-paced introduction to modern large language model systems.",
    canonicalUrl: "https://opencoursemap.dev/demo/llm-foundations",
    enrollmentUrl: "https://www.deeplearning.ai/short-courses/",
    providerId: "provider-deeplearning",
    topicIds: ["topic-llm", "topic-genai", "topic-prompt"],
    skillIds: ["skill-model-selection", "skill-prompt-evals"],
    difficulty: "basic",
    durationHours: 5,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: "2026-03-01T10:00:00.000Z",
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "OpenCourseMap Demo",
    prerequisiteText: "Basic Python familiarity helps.",
    syllabus: "LLM basics, prompting, retrieval, evaluation.",
    publishedAt: "2026-01-04T10:00:00.000Z",
  },
  {
    id: "course-rag-practical",
    title: "Practical RAG Systems",
    summary: "Learn retrieval pipelines, chunking, ranking, and evaluation for RAG applications.",
    canonicalUrl: "https://opencoursemap.dev/demo/practical-rag",
    enrollmentUrl: "https://huggingface.co/learn",
    providerId: "provider-hf",
    topicIds: ["topic-rag", "topic-vector", "topic-eval"],
    skillIds: ["skill-rag-architecture", "skill-prompt-evals"],
    difficulty: "amateur",
    durationHours: 8,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: "2026-03-04T10:00:00.000Z",
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: true,
    certificateIsFree: false,
    instructorName: "Community Team",
    prerequisiteText: "LLM basics and embeddings concepts.",
    syllabus: "Indexing, embeddings, retrieval, evals, ops.",
    publishedAt: "2026-02-10T10:00:00.000Z",
  },
  {
    id: "course-mcp-builder",
    title: "Build with MCP",
    summary: "A guided introduction to Model Context Protocol concepts and tool-enabled apps.",
    canonicalUrl: "https://opencoursemap.dev/demo/build-with-mcp",
    enrollmentUrl: "https://huggingface.co/learn",
    providerId: "provider-hf",
    topicIds: ["topic-mcp", "topic-agents"],
    skillIds: ["skill-agent-tooling"],
    difficulty: "amateur",
    durationHours: 4,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: "2026-03-08T10:00:00.000Z",
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Platform Engineering",
    syllabus: "Protocol primitives, tools, sessions, server design.",
    publishedAt: "2026-02-18T10:00:00.000Z",
  },
  {
    id: "course-ml-refresher",
    title: "Machine Learning Refresher",
    summary: "Refresh the statistics and ML foundations needed for advanced GenAI work.",
    canonicalUrl: "https://opencoursemap.dev/demo/ml-refresher",
    enrollmentUrl: "https://www.coursera.org",
    providerId: "provider-coursera",
    topicIds: ["topic-ml", "topic-stats", "topic-python"],
    skillIds: ["skill-feature-engineering"],
    difficulty: "basic",
    durationHours: 12,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: "2026-02-22T10:00:00.000Z",
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: true,
    certificateIsFree: false,
    instructorName: "University Partner",
    syllabus: "Python, statistics, experimentation, classical ML.",
    publishedAt: "2025-12-14T10:00:00.000Z",
  },
  {
    id: "course-responsible-agents",
    title: "Responsible AI Agents",
    summary: "Operational and policy guardrails for agentic systems shipped to users.",
    canonicalUrl: "https://opencoursemap.dev/demo/responsible-agents",
    enrollmentUrl: "https://www.deeplearning.ai/short-courses/",
    providerId: "provider-deeplearning",
    topicIds: ["topic-agents", "topic-rai", "topic-eval"],
    skillIds: ["skill-agent-tooling", "skill-safety-review"],
    difficulty: "professional",
    durationHours: 7,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "suspected",
    freeVerifiedAt: "2026-01-28T10:00:00.000Z",
    isActive: true,
    courseMode: "cohort",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Safety Team",
    syllabus: "Threat modeling, evals, tool risk, governance.",
    publishedAt: "2026-02-26T10:00:00.000Z",
  },
  {
    id: "course-finetuning-ops",
    title: "Fine-Tuning and MLOps",
    summary: "Bridge experimentation and operations for adapted language models.",
    canonicalUrl: "https://opencoursemap.dev/demo/fine-tuning-ops",
    enrollmentUrl: "https://www.coursera.org",
    providerId: "provider-coursera",
    topicIds: ["topic-finetune", "topic-mlops", "topic-llm"],
    skillIds: ["skill-model-selection", "skill-safety-review"],
    difficulty: "professional",
    durationHours: 10,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: "2026-03-10T10:00:00.000Z",
    isActive: true,
    courseMode: "live",
    hasCertificate: true,
    certificateIsFree: true,
    instructorName: "Ops Faculty",
    syllabus: "Data prep, fine-tune loops, deployment, observability.",
    publishedAt: "2026-01-30T10:00:00.000Z",
  },
  {
    id: "course-openai-academy",
    title: "OpenAI Academy",
    summary:
      "OpenAI's official academy hub with workshops, guides, and practical AI learning tracks for builders, educators, and community cohorts.",
    canonicalUrl: "https://academy.openai.com/",
    enrollmentUrl: "https://academy.openai.com/",
    providerId: "provider-openai",
    topicIds: ["topic-llm", "topic-prompt", "topic-agents"],
    skillIds: ["skill-model-selection", "skill-prompt-evals"],
    difficulty: "amateur",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "hybrid",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "OpenAI Academy",
    prerequisiteText: "No prerequisite for academy browsing; specific sessions may target different levels.",
    syllabus: "Workshops, prompts, classroom use, building blocks, and community programming.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-anthropic-learn",
    title: "Anthropic Academy",
    summary:
      "Anthropic's official learning hub for Claude guides, prompting, evaluation, safety, and enterprise adoption patterns.",
    canonicalUrl: "https://www.anthropic.com/learn",
    enrollmentUrl: "https://www.anthropic.com/learn",
    providerId: "provider-anthropic",
    topicIds: ["topic-llm", "topic-prompt", "topic-rai"],
    skillIds: ["skill-prompt-evals", "skill-safety-review"],
    difficulty: "amateur",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Anthropic Team",
    prerequisiteText: "Helpful if you already understand basic LLM concepts.",
    syllabus: "Claude usage patterns, safe deployment, prompting, and product workflows.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-linkedin-genai-path",
    title: "Career Essentials in Generative AI by Microsoft and LinkedIn",
    summary:
      "A LinkedIn Learning path covering generative AI foundations, responsible usage, and practical workplace adoption patterns.",
    canonicalUrl:
      "https://www.linkedin.com/learning/paths/career-essentials-in-generative-ai-by-microsoft-and-linkedin",
    enrollmentUrl:
      "https://www.linkedin.com/learning/paths/career-essentials-in-generative-ai-by-microsoft-and-linkedin",
    providerId: "provider-linkedin",
    topicIds: ["topic-genai", "topic-llm", "topic-rai"],
    skillIds: ["skill-model-selection", "skill-prompt-evals"],
    difficulty: "basic",
    durationHours: 4,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "suspected",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: true,
    certificateIsFree: false,
    instructorName: "Microsoft and LinkedIn",
    prerequisiteText: "No prerequisites listed.",
    syllabus: "Generative AI basics, productivity use cases, responsible practices, and foundational prompting.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-microsoft-genai-beginners",
    title: "Generative AI for Beginners",
    summary:
      "Microsoft's official beginner series introducing generative AI concepts, LLM applications, prompt design, and app-building patterns.",
    canonicalUrl: "https://microsoft.github.io/generative-ai-for-beginners/",
    enrollmentUrl: "https://microsoft.github.io/generative-ai-for-beginners/",
    providerId: "provider-microsoft",
    topicIds: ["topic-genai", "topic-llm", "topic-prompt"],
    skillIds: ["skill-model-selection", "skill-prompt-evals"],
    difficulty: "basic",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Microsoft Learn",
    prerequisiteText: "Helpful if you know basic programming concepts.",
    syllabus: "Generative AI concepts, prompts, responsible AI, apps, and deployment basics.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-ibm-ai-foundations",
    title: "IBM SkillsBuild AI Foundations",
    summary:
      "IBM's official SkillsBuild catalog entry for foundational AI literacy, core concepts, and responsible deployment themes.",
    canonicalUrl: "https://skillsbuild.org/learn",
    enrollmentUrl: "https://skillsbuild.org/learn",
    providerId: "provider-ibm",
    topicIds: ["topic-ml", "topic-genai", "topic-rai"],
    skillIds: ["skill-feature-engineering", "skill-model-selection"],
    difficulty: "basic",
    durationHours: 15,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "IBM SkillsBuild",
    prerequisiteText: "No prerequisites listed.",
    syllabus: "AI basics, machine learning concepts, ethics, and practical business context.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-aws-genai-dev-hour",
    title: "AWS Dev Hour: Learn Gen AI from Scratch!",
    summary:
      "AWS's official training series for GenAI newcomers covering foundations, current tooling, and a path into hands-on building.",
    canonicalUrl: "https://aws.amazon.com/training/learn-about/generative-ai/",
    enrollmentUrl: "https://aws.amazon.com/training/learn-about/generative-ai/",
    providerId: "provider-aws",
    topicIds: ["topic-genai", "topic-llm", "topic-agents"],
    skillIds: ["skill-model-selection", "skill-agent-tooling"],
    difficulty: "amateur",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "AWS Training and Certification",
    prerequisiteText: "Beginner-friendly entry point.",
    syllabus: "GenAI fundamentals, AWS tooling landscape, and practical next steps.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-google-intro-genai",
    title: "Introduction to Generative AI",
    summary:
      "Google Cloud Skills Boost microlearning course explaining what generative AI is, common model types, and main use cases.",
    canonicalUrl: "https://www.cloudskillsboost.google/course_templates/536",
    enrollmentUrl: "https://www.cloudskillsboost.google/course_templates/536",
    providerId: "provider-google",
    topicIds: ["topic-genai", "topic-llm", "topic-rai"],
    skillIds: ["skill-model-selection", "skill-prompt-evals"],
    difficulty: "basic",
    durationHours: 0.75,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Google Cloud Skills Boost",
    prerequisiteText: "No prerequisites listed.",
    syllabus: "Generative AI definition, model families, and high-level application patterns.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-perplexity-cookbook",
    title: "Perplexity API Cookbook",
    summary:
      "Perplexity's official cookbook with practical examples for building search-augmented AI experiences using the Perplexity API.",
    canonicalUrl: "https://docs.perplexity.ai/cookbook/getting_started",
    enrollmentUrl: "https://docs.perplexity.ai/cookbook/getting_started",
    providerId: "provider-perplexity",
    topicIds: ["topic-llm", "topic-agents", "topic-rag"],
    skillIds: ["skill-agent-tooling", "skill-prompt-evals"],
    difficulty: "amateur",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Perplexity Developer Docs",
    prerequisiteText: "Helpful if you are comfortable with APIs and prompt-driven workflows.",
    syllabus: "Getting started, request patterns, citations, and application recipes.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-meta-open-source-ai",
    title: "Open Source AI by Meta",
    summary:
      "Meta's official open-source AI resource hub for Llama models, toolkits, community programs, and getting-started materials.",
    canonicalUrl: "https://www.meta.com/ai/open-source/",
    enrollmentUrl: "https://www.meta.com/ai/open-source/",
    providerId: "provider-meta",
    topicIds: ["topic-llm", "topic-ml", "topic-rai"],
    skillIds: ["skill-model-selection", "skill-safety-review"],
    difficulty: "amateur",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Meta AI",
    prerequisiteText: "Useful if you want an overview of the Meta open model ecosystem.",
    syllabus: "Llama resources, tooling, programs, and open model adoption guidance.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
  {
    id: "course-tesla-ai-robotics",
    title: "Tesla AI & Robotics",
    summary:
      "Tesla's official AI and robotics resource hub covering autonomy, Optimus, dojo-scale training, and engineering context for applied ML systems.",
    canonicalUrl: "https://www.tesla.com/AI",
    enrollmentUrl: "https://www.tesla.com/AI",
    providerId: "provider-tesla",
    topicIds: ["topic-ml", "topic-eval", "topic-mlops"],
    skillIds: ["skill-feature-engineering", "skill-safety-review"],
    difficulty: "professional",
    durationHours: null,
    languageCode: "en",
    isFree: true,
    freeVerificationStatus: "verified",
    freeVerifiedAt: catalogVerifiedAt,
    isActive: true,
    courseMode: "self-paced",
    hasCertificate: false,
    certificateIsFree: false,
    instructorName: "Tesla AI",
    prerequisiteText: "Best for learners interested in applied ML systems and robotics.",
    syllabus: "Autonomy stack context, robotics, training infrastructure, and engineering overviews.",
    publishedAt: "2026-03-15T09:00:00.000Z",
  },
];

export const learningPaths: LearningPath[] = [
  {
    id: "path-foundations",
    slug: "generative-ai-foundations",
    title: "Generative AI Foundations",
    description: "A guided path from Python and ML basics into practical LLM workflows.",
    targetLevel: "basic",
    topicId: "topic-genai",
    isPublished: true,
    items: [
      {
        id: "path-foundations-1",
        courseId: "course-ml-refresher",
        sequenceNo: 1,
        isRequired: true,
        rationale: "Establishes Python and ML vocabulary.",
      },
      {
        id: "path-foundations-2",
        courseId: "course-llm-foundations",
        sequenceNo: 2,
        isRequired: true,
        rationale: "Introduces modern LLM workflows after ML fundamentals.",
      },
      {
        id: "path-foundations-3",
        courseId: "course-rag-practical",
        sequenceNo: 3,
        isRequired: false,
        rationale: "Adds retrieval and evaluation once basics are stable.",
      },
    ],
  },
  {
    id: "path-llm-pro",
    slug: "professional-llm-engineer-path",
    title: "Professional LLM Engineer Path",
    description: "Production-oriented track covering RAG, MCP, agent systems, and operations.",
    targetLevel: "professional",
    topicId: "topic-llm",
    isPublished: true,
    items: [
      {
        id: "path-llm-pro-1",
        courseId: "course-llm-foundations",
        sequenceNo: 1,
        isRequired: true,
        rationale: "Sets common modeling and prompting context.",
      },
      {
        id: "path-llm-pro-2",
        courseId: "course-rag-practical",
        sequenceNo: 2,
        isRequired: true,
        rationale: "Covers core retrieval architecture skills.",
      },
      {
        id: "path-llm-pro-3",
        courseId: "course-mcp-builder",
        sequenceNo: 3,
        isRequired: true,
        rationale: "Introduces tool and protocol integration.",
      },
      {
        id: "path-llm-pro-4",
        courseId: "course-finetuning-ops",
        sequenceNo: 4,
        isRequired: true,
        rationale: "Adds production operations and lifecycle concerns.",
      },
      {
        id: "path-llm-pro-5",
        courseId: "course-responsible-agents",
        sequenceNo: 5,
        isRequired: false,
        rationale: "Strengthens governance and safety readiness.",
      },
    ],
  },
];

export const sources: SourceConfig[] = [
  {
    id: "source-manual-demo",
    name: "Manual curation",
    baseUrl: "https://opencoursemap.dev/manual",
    sourceType: "manual",
    parserKey: "manualAdapter",
    cadence: "ad-hoc",
    termsReviewed: true,
    robotsReviewed: true,
    enabled: true,
  },
  {
    id: "source-rss-demo",
    name: "Provider feed",
    baseUrl: "https://example.com/feed.xml",
    sourceType: "rss",
    parserKey: "rssAdapter",
    cadence: "daily",
    termsReviewed: true,
    robotsReviewed: true,
    enabled: true,
  },
];

export const sourceRuns: SourceRun[] = [
  {
    id: "run-demo-1",
    sourceId: "source-rss-demo",
    status: "succeeded",
    startedAt: "2026-03-14T07:00:00.000Z",
    finishedAt: "2026-03-14T07:02:00.000Z",
    discoveredCount: 8,
    insertedCount: 2,
    updatedCount: 3,
    rejectedCount: 3,
  },
];

export const ingestionCandidates: IngestionCandidate[] = [
  {
    id: "candidate-1",
    sourceRunId: "run-demo-1",
    discoveredUrl: "https://example.com/free-mcp-course",
    canonicalUrl: "https://example.com/free-mcp-course",
    title: "Free MCP Course",
    parseStatus: "needs_review",
    confidenceScore: 0.82,
    metadata: {
      providerName: "Example Provider",
      topicSlugs: ["mcp", "ai-agents"],
      difficulty: "amateur",
    },
  },
  {
    id: "candidate-2",
    sourceRunId: "run-demo-1",
    discoveredUrl: "https://example.com/paid-course",
    title: "Likely Paid Course",
    parseStatus: "rejected",
    confidenceScore: 0.48,
    metadata: {
      reason: "Pricing wall detected",
    },
    rejectionReason: "Pricing wall detected",
  },
];

export const demoProfile: UserProfile = {
  id: "user-demo-1",
  email: "learner@opencoursemap.dev",
  fullName: "Demo Learner",
  headline: "Building toward production LLM engineering.",
  currentLevel: "amateur",
  weeklyStudyHours: 8,
  avatarUrl: "",
  isAdmin: true,
};

export const demoPreferences: UserPreferences = {
  userId: "user-demo-1",
  goalText: "Ship reliable LLM applications with retrieval and evaluation.",
  preferredLevel: "professional",
  preferredLanguageCode: "en",
  wantsCertificates: false,
  prefersSelfPaced: true,
  preferredTopics: ["topic-llm", "topic-rag", "topic-eval", "topic-mcp"],
  preferredProviders: ["provider-deeplearning", "provider-hf"],
};

export const userCourseStatuses: UserCourseStatus[] = [
  {
    id: "ucs-1",
    userId: "user-demo-1",
    courseId: "course-llm-foundations",
    status: "completed",
    percentComplete: 100,
    startedAt: "2026-02-01T10:00:00.000Z",
    completedAt: "2026-02-07T10:00:00.000Z",
    completionNotes: "Strong fundamentals on prompting and evaluation.",
    hoursSpent: 5,
    rating: 4,
    updatedAt: now,
  },
  {
    id: "ucs-2",
    userId: "user-demo-1",
    courseId: "course-rag-practical",
    status: "in_progress",
    percentComplete: 45,
    enrolledAt: "2026-03-01T10:00:00.000Z",
    startedAt: "2026-03-02T10:00:00.000Z",
    completionNotes: "Working through retrieval evals.",
    hoursSpent: 3.5,
    updatedAt: now,
  },
  {
    id: "ucs-3",
    userId: "user-demo-1",
    courseId: "course-mcp-builder",
    status: "bookmarked",
    percentComplete: 0,
    hoursSpent: 0,
    updatedAt: now,
  },
];

export function getDemoProfile() {
  return demoProfile;
}
